### ISSUE TITLE
Installer script requries software-properties-common

### ISSUE THREAD

**Issue by henroFall** [itiligent/Guacamole-Setup#7] opened 2023-06-04 01:11 UTC
Must:
apt install software-properties-common 

before the install script can complete. It will otherwise error out on a fresh Ubuntu 20.04 server

**Comment by itiligent** [comment] 2023-06-04 07:19
Hi and thanks for your input.

I just checked and I can confirm that a vanilla Ubuntu 20.04.6 install from latest iso already includes software-properties-common by default. Same for Ubuntu 22.x and Debian 11. So, this point might need a little further investigation at your end.

To be suree I ran up another test on Ubuntu 20.04.6,  22.04.2 and Debian 11 and I can confirm it all installs perfectly on all flavours with all SSL install options added. Heres a few suggestions for you and perhaps others reading this...

1. The only difference between Debian and Ubuntu installs is that on Ubuntu the installer prompts for the root sql password if the mysql_seqcure_installation is selected. Deban skips  this check if you are already sudo. Therefore on Ubuntu if you dont use the exact same password as the one was entered at the start of the script for the sql root pw it will error out. This quirk will breaks a full unattended mass server deployment and perhaps I'll look into that quirk someday - but typically mass deployments will run Debian/RHEL anyway.... trust me in that Guacolme is much slower under Ubuntu.   
 
2. Did you install Ubuntu 20.0.4 with lastest 20.04.6 media and did you also choose to udate the Ubuntu installer when first starting to run Ubuntu 20.04 installer iso? A few repo chages occurred a little after the time of the 20.04 release I think. 

3. Software proerties-common is related to repo mangement.  Do you have anything else funky going on with repo's youve added or tweaked? 

Any extra info you can supply will be helpful as I cant reproduce your error with the info supplied.

thanks again.

**Comment by itiligent** [comment] 2023-06-09 07:45
closing this as supplied info cant reproduce the error

**Comment by itiligent** [comment] 2023-06-09 07:47
Closing this as claimed info conflicts with Ubuntu defaults settings, cant reproduce.

**Closed by itiligent** 2023-06-09 07:47 UTC

**Comment by henroFall** [comment] 2023-06-09 10:06
Thank you for the follow up! I was using an older iso of 20.04. I expect
that we're I to use the latest as you suggest, that I would not have the
issue.

My fault, sorry for the confusion.

BR,
Henry
