### ISSUE TITLE
Errors on RDP and SSH

### ISSUE THREAD

**Issue by tiwale01** [itiligent/Guacamole-Setup#6] opened 2023-05-17 14:31 UTC
May 17 13:15:35 guac1 tomcat9[727]: 13:15:35.993 [http-nio-8080-exec-7] ERROR o.a.g.w.GuacamoleWebSocketTunnelEndpoint - Creation of WebSocket tunnel to guacd failed: Non-numeric character in element length.

May 17 13:15:36 guac1 tomcat9[727]: 13:15:36.028 [http-nio-8080-exec-2] ERROR o.a.g.s.GuacamoleHTTPTunnelServlet - HTTP tunnel request failed: Non-numeric character in element length.

I added # to ::1 in hosts, checked guacd.conf

What else do I check, not much in syslog and catalina

Tried on both Debian 11 and Unbuntu 22.x

**Comment by itiligent** [comment] 2023-05-18 03:30
To be sure I just ran up a fresh debian 11 and installed the full suite of add on scripts and then tested RDP with win11 down to winxp - it all works perfectly at my end in a vanilla dev enviroment.  Logs ware not saying much as there is not much to say on the guacamole part. This means you are going to need to look deeper into your local configuration as this is more than likely to do with either the connection options you are passing guacamole or the compatibiltiy of these settings with other factors in your network like filters, proxy, non standard ports, ipv6, or host congirautons with certificates, spaces in names  etc. Normal trouble shooting elimination steps apply - start with a vanilla RDP connection to a fresh hosted in same network and test.  Then add the layers from there. Personally I'd start to test with ipv6 disabled to eliminate a range of quirks - if this is possible fo you

**Comment by tiwale01** [comment] 2023-05-18 20:29
Hi, I just tried with a clean install on a new virtualbox install. same error as before. Do you do anything else after. This is the only command I ran and I disabled ipv6 in grub  before running. It's strange 2 different VM. 1 in proxmox, another in Virtualbox producign the same error. Unless that script does not run inside VM, I do not see what else it can be.

wget https://raw.githubusercontent.com/itiligent/Guacamole-Setup/main/1-setup.sh && chmod +x 1-setup.sh && ./1-setup.sh

**Comment by emiliano-colli** [comment] 2023-05-18 21:13
Hi,
I am using an official Proxmox wrapper based on Debian 11 and it works
perfectly.

The only thing I did besides was update the OS and open the firewall ports
that seemed necessary to me.

Did you open the firewall ports of the Guacamole VM ?
Can you  verify Nginx for any configuration errors : nginx -t

- Allow Nginx on Firewall
If UFW is running, allow access to Nginx : ufw allow 'Nginx Full'

ufw allow 'Nginx HTTP'
ufw allow 'Nginx HTTPS'

The above command open ports 80 (HTTP) and 443 (HTTPS) on firewall.

If you need to open just port 80 (allow HTTP traffic) or port 443 (allow
HTTPS traffic), you can run either of the commands below respectively.

Tomcat :
ufw allow 8080

Emiliano.

**Comment by tiwale01** [comment] 2023-05-18 21:25
I am not using firewall

strange, in this debian 11, it did not install ngingx

root@guac1:~# nginx -t
-bash: nginx: command not found

**Comment by itiligent** [comment] 2023-05-19 03:13
Nginx is installed only if you selected this option.  An understanding of file paths and sudo may help in how you are navigating your tests .. eg.. you need to run commands in the relative right path and often with sudo unless you customse your paths
user@guac:~$ cd /etc/nginx/
user@guac:/etc/nginx$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

On your other issue, unfortunately we are shooting blind here. Please understand its not easy to help you without any context such as: 
1.  Your server environment, all tasks it runs and what else is installed, how many NICs etc, is Docker also present?
2.  The RDP hosts you are trying to connect and their own specific configuration (authentication requires certificates? AD security policy?) 
3.  The EXACT options you have used to configure your guacamole server (this is really important ie you cant run self signed and LetsEncrpyt on the same config/instance of Nginx)
5. Context of network and the full data path from server to client, and any filters in between. Non standard ports

Becasue your error cannot be replicated in a single server/single network test environemnt in both ESXI and proxmox ,then, by defintion, the issues must lie with the configuration components that fall outside of this. 

So, please go back to first principles of troubleshooting and methodically, and thoroughly, step through each component to evaluate it. The errors you are seeing will almost certainly realte to your local environmental setup, your VM enviroment or the 
specific config you are setting for guacamole connections to RDP hosts, or some combination of all. 

The best thing I can suggest is that you build and test with a fresh vanilla Linux VM, on a vanilla VLAN and with a vanilla windows client all in the SAME network as the guac server to start with. Use only the setup  script to start with, (dont add LDAP,DUO orTotp at this point.) You could even do an install without nginx first, then with nginx, then with nginx ssl. The idea is to keep adding layers until it breaks.

**Comment by itiligent** [comment] 2023-05-19 03:39
just had another thought... are you sure all the required packages are downloading sucessfully? Do you have any DNS / AV / endpoint filters or geoblockers in place - I've seen this somtimes and setting local mirrors can help. The install script will continue with any download errors giving you a skeleton system that could look like what you are seeing.   Virtual box also needs a bridged network setup , not NAT which I think is the default. I've also run this up in VMworkstation on debian 11 with IPv6 and bridged network and it works fine. Are you sure all the whole suite of 13 scripts are downloading?

**Comment by itiligent** [comment] 2023-06-04 06:58
closing due to error not being reproducable with the given info

**Closed by itiligent** 2023-06-04 06:58 UTC
